// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOSPDpnDOKqZnd1zxDibNbN-gGkswX104',
    appId: '1:802457816387:web:2f825cbd1e86c6589ef3f6',
    messagingSenderId: '802457816387',
    projectId: 'gs-social-1187a',
    authDomain: 'gs-social-1187a.firebaseapp.com',
    storageBucket: 'gs-social-1187a.appspot.com',
    measurementId: 'G-1CHF94HWTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1SU0Z0jAmUhSUq63RoBy75Houk7Yw93o',
    appId: '1:802457816387:android:ad48a5e09467be2b9ef3f6',
    messagingSenderId: '802457816387',
    projectId: 'gs-social-1187a',
    storageBucket: 'gs-social-1187a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXkKxIzIm7rNw4DquJ0dEAxCrG9ekuSGA',
    appId: '1:802457816387:ios:d1416e30fcaba60a9ef3f6',
    messagingSenderId: '802457816387',
    projectId: 'gs-social-1187a',
    storageBucket: 'gs-social-1187a.appspot.com',
    iosBundleId: 'com.example.gsSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXkKxIzIm7rNw4DquJ0dEAxCrG9ekuSGA',
    appId: '1:802457816387:ios:d1416e30fcaba60a9ef3f6',
    messagingSenderId: '802457816387',
    projectId: 'gs-social-1187a',
    storageBucket: 'gs-social-1187a.appspot.com',
    iosBundleId: 'com.example.gsSocial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOSPDpnDOKqZnd1zxDibNbN-gGkswX104',
    appId: '1:802457816387:web:117a542b41a1f2b19ef3f6',
    messagingSenderId: '802457816387',
    projectId: 'gs-social-1187a',
    authDomain: 'gs-social-1187a.firebaseapp.com',
    storageBucket: 'gs-social-1187a.appspot.com',
    measurementId: 'G-1VCYDM5ZQW',
  );

}